--2025-03-31 22:12:49--  https://fbsub.cyou/api/v1/client/subscribe?token=fc6f2551af997c28da7348ca3834c345
Resolving fbsub.cyou (fbsub.cyou)... 23.145.136.241
Connecting to fbsub.cyou (fbsub.cyou)|23.145.136.241|:443... connected.
HTTP request sent, awaiting response... 